name = "carchelin"
compatibility_date = "2024-01-01"

# 정적 파일 제공
[site]
bucket = "."
include = ["index.html", "assets_rent/**/*"]

# KV 네임스페이스 바인딩
[[kv_namespaces]]
binding = "CAR_DB"
id = "7988f4f4331d4a2385819947b54fa062"
preview_id = "7988f4f4331d4a2385819947b54fa062"
